version: "3"
services:

  service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/home/node/app/src
      - ./npm:/home/node/app/npm
      - ./lib:/home/node/app/lib
      - ./schemas:/home/node/app/schemas
      - ./package.json:/home/node/app/package.json
      - ./ecosystem.config.js:/home/node/app/ecosystem.config.js
    environment:
      - NODE_ENV=development
      - AUTH_METHOD=${AUTH_METHOD}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_CALLBACK_URL=${GITHUB_CALLBACK_URL}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_SERVER=${REDIS_SERVER}
      - REDIS_DB=${REDIS_DB}
      - SERVER_PORT=${SERVER_PORT:-3000}
    ports:
      - "${SERVER_PORT:-3000}:${SERVER_PORT:-3000}"
    depends_on:
      - redis

  redis:
    image: redis:5
    ports:
      - "6379:6379"
    volumes:
      - ./var/redis:/data
    entrypoint: redis-server --appendonly yes
